import { StrengthTheme, Question } from './types';

export const STRENGTH_THEMES: StrengthTheme[] = [
  // Executing
  { name: 'Achiever', domain: 'Executing' },
  { name: 'Arranger', domain: 'Executing' },
  { name: 'Belief', domain: 'Executing' },
  { name: 'Consistency', domain: 'Executing' },
  { name: 'Deliberative', domain: 'Executing' },
  { name: 'Discipline', domain: 'Executing' },
  { name: 'Focus', domain: 'Executing' },
  { name: 'Responsibility', domain: 'Executing' },
  { name: 'Restorative', domain: 'Executing' },

  // Influencing
  { name: 'Activator', domain: 'Influencing' },
  { name: 'Command', domain: 'Influencing' },
  { name: 'Communication', domain: 'Influencing' },
  { name: 'Competition', domain: 'Influencing' },
  { name: 'Maximizer', domain: 'Influencing' },
  { name: 'Self-Assurance', domain: 'Influencing' },
  { name: 'Significance', domain: 'Influencing' },
  { name: 'Woo', domain: 'Influencing' },

  // Relationship Building
  { name: 'Adaptability', domain: 'Relationship Building' },
  { name: 'Connectedness', domain: 'Relationship Building' },
  { name: 'Developer', domain: 'Relationship Building' },
  { name: 'Empathy', domain: 'Relationship Building' },
  { name: 'Harmony', domain: 'Relationship Building' },
  { name: 'Includer', domain: 'Relationship Building' },
  { name: 'Individualization', domain: 'Relationship Building' },
  { name: 'Positivity', domain: 'Relationship Building' },
  { name: 'Relator', domain: 'Relationship Building' },

  // Strategic Thinking
  { name: 'Analytical', domain: 'Strategic Thinking' },
  { name: 'Context', domain: 'Strategic Thinking' },
  { name: 'Futuristic', domain: 'Strategic Thinking' },
  { name: 'Ideation', domain: 'Strategic Thinking' },
  { name: 'Input', domain: 'Strategic Thinking' },
  { name: 'Intellection', domain: 'Strategic Thinking' },
  { name: 'Learner', domain: 'Strategic Thinking' },
  { name: 'Strategic', domain: 'Strategic Thinking' },
];

export const QUESTIONS: Question[] = [
  { id: '1', domainA: 'Executing', domainB: 'Relationship Building', themesA: ['Discipline', 'Focus'], themesB: ['Adaptability'] },
  { id: '2', domainA: 'Influencing', domainB: 'Strategic Thinking', themesA: ['Woo'], themesB: ['Analytical'] },
  { id: '3', domainA: 'Relationship Building', domainB: 'Executing', themesA: ['Developer'], themesB: ['Consistency'] },
  { id: '4', domainA: 'Influencing', domainB: 'Relationship Building', themesA: ['Command'], themesB: ['Empathy'] },
  { id: '5', domainA: 'Strategic Thinking', domainB: 'Executing', themesA: ['Futuristic', 'Ideation'], themesB: ['Responsibility'] },
  { id: '6', domainA: 'Strategic Thinking', domainB: 'Executing', themesA: ['Intellection'], themesB: ['Arranger'] },
  { id: '7', domainA: 'Influencing', domainB: 'Strategic Thinking', themesA: ['Competition'], themesB: ['Input'] },
  { id: '8', domainA: 'Relationship Building', domainB: 'Influencing', themesA: ['Adaptability'], themesB: ['Self-Assurance'] },
  { id: '9', domainA: 'Relationship Building', domainB: 'Executing', themesA: ['Individualization'], themesB: ['Deliberative'] },
  { id: '10', domainA: 'Influencing', domainB: 'Strategic Thinking', themesA: ['Communication'], themesB: ['Context'] },

  // Executing vs Influencing
  { id: '11', domainA: 'Executing', domainB: 'Influencing', themesA: ['Achiever', 'Responsibility'], themesB: ['Activator'] },
  { id: '12', domainA: 'Executing', domainB: 'Influencing', themesA: ['Discipline'], themesB: ['Command'] },
  { id: '13', domainA: 'Executing', domainB: 'Influencing', themesA: ['Belief'], themesB: ['Communication'] },
  { id: '14', domainA: 'Executing', domainB: 'Influencing', themesA: ['Achiever'], themesB: ['Competition'] },
  { id: '15', domainA: 'Executing', domainB: 'Influencing', themesA: ['Restorative'], themesB: ['Maximizer'] },
  { id: '16', domainA: 'Executing', domainB: 'Influencing', themesA: ['Responsibility'], themesB: ['Self-Assurance'] },
  { id: '17', domainA: 'Executing', domainB: 'Influencing', themesA: ['Focus'], themesB: ['Significance'] },
  { id: '18', domainA: 'Executing', domainB: 'Influencing', themesA: ['Consistency'], themesB: ['Woo'] },
  { id: '19', domainA: 'Executing', domainB: 'Influencing', themesA: ['Deliberative', 'Responsibility'], themesB: ['Activator'] },
  { id: '20', domainA: 'Executing', domainB: 'Influencing', themesA: ['Arranger'], themesB: ['Command'] },
  { id: '21', domainA: 'Executing', domainB: 'Influencing', themesA: ['Achiever'], themesB: ['Significance'] },
  { id: '22', domainA: 'Executing', domainB: 'Influencing', themesA: ['Discipline'], themesB: ['Communication'] },
  { id: '23', domainA: 'Executing', domainB: 'Influencing', themesA: ['Restorative'], themesB: ['Competition'] },
  { id: '24', domainA: 'Executing', domainB: 'Influencing', themesA: ['Belief'], themesB: ['Maximizer'] },
  { id: '25', domainA: 'Executing', domainB: 'Influencing', themesA: ['Focus'], themesB: ['Self-Assurance'] },

  // Executing vs Relationship Building
  { id: '26', domainA: 'Executing', domainB: 'Relationship Building', themesA: ['Achiever'], themesB: ['Empathy'] },
  { id: '27', domainA: 'Executing', domainB: 'Relationship Building', themesA: ['Arranger'], themesB: ['Harmony'] },
  { id: '28', domainA: 'Executing', domainB: 'Relationship Building', themesA: ['Discipline'], themesB: ['Adaptability'] },
  { id: '29', domainA: 'Executing', domainB: 'Relationship Building', themesA: ['Belief'], themesB: ['Connectedness'] },
  { id: '30', domainA: 'Executing', domainB: 'Relationship Building', themesA: ['Consistency'], themesB: ['Includer'] },
  { id: '31', domainA: 'Executing', domainB: 'Relationship Building', themesA: ['Restorative'], themesB: ['Developer'] },
  { id: '32', domainA: 'Executing', domainB: 'Relationship Building', themesA: ['Responsibility'], themesB: ['Relator'] },
  { id: '33', domainA: 'Executing', domainB: 'Relationship Building', themesA: ['Focus'], themesB: ['Positivity'] },
  { id: '34', domainA: 'Executing', domainB: 'Relationship Building', themesA: ['Deliberative'], themesB: ['Adaptability'] },
  { id: '35', domainA: 'Executing', domainB: 'Relationship Building', themesA: ['Achiever'], themesB: ['Positivity'] },
  { id: '36', domainA: 'Executing', domainB: 'Relationship Building', themesA: ['Arranger'], themesB: ['Individualization'] },
  { id: '37', domainA: 'Executing', domainB: 'Relationship Building', themesA: ['Discipline'], themesB: ['Connectedness'] },
  { id: '38', domainA: 'Executing', domainB: 'Relationship Building', themesA: ['Belief'], themesB: ['Empathy'] },
  { id: '39', domainA: 'Executing', domainB: 'Relationship Building', themesA: ['Restorative'], themesB: ['Harmony'] },
  { id: '40', domainA: 'Executing', domainB: 'Relationship Building', themesA: ['Consistency'], themesB: ['Relator'] },

  // Executing vs Strategic Thinking
  { id: '41', domainA: 'Executing', domainB: 'Strategic Thinking', themesA: ['Achiever'], themesB: ['Learner'] },
  { id: '42', domainA: 'Executing', domainB: 'Strategic Thinking', themesA: ['Arranger', 'Deliberative'], themesB: ['Strategic'] },
  { id: '43', domainA: 'Executing', domainB: 'Strategic Thinking', themesA: ['Discipline'], themesB: ['Ideation'] },
  { id: '44', domainA: 'Executing', domainB: 'Strategic Thinking', themesA: ['Belief'], themesB: ['Intellection'] },
  { id: '45', domainA: 'Executing', domainB: 'Strategic Thinking', themesA: ['Consistency'], themesB: ['Analytical'] },
  { id: '46', domainA: 'Executing', domainB: 'Strategic Thinking', themesA: ['Deliberative'], themesB: ['Futuristic'] },
  { id: '47', domainA: 'Executing', domainB: 'Strategic Thinking', themesA: ['Focus'], themesB: ['Input'] },
  { id: '48', domainA: 'Executing', domainB: 'Strategic Thinking', themesA: ['Responsibility'], themesB: ['Strategic'] },
  { id: '49', domainA: 'Executing', domainB: 'Strategic Thinking', themesA: ['Restorative'], themesB: ['Analytical'] },
  { id: '50', domainA: 'Executing', domainB: 'Strategic Thinking', themesA: ['Achiever'], themesB: ['Ideation'] },
  { id: '51', domainA: 'Executing', domainB: 'Strategic Thinking', themesA: ['Arranger'], themesB: ['Context'] },
  { id: '52', domainA: 'Executing', domainB: 'Strategic Thinking', themesA: ['Discipline'], themesB: ['Learner'] },
  { id: '53', domainA: 'Executing', domainB: 'Strategic Thinking', themesA: ['Belief'], themesB: ['Futuristic'] },
  { id: '54', domainA: 'Executing', domainB: 'Strategic Thinking', themesA: ['Consistency'], themesB: ['Intellection'] },
  { id: '55', domainA: 'Executing', domainB: 'Strategic Thinking', themesA: ['Focus'], themesB: ['Context'] },

  // Influencing vs Relationship Building
  { id: '56', domainA: 'Influencing', domainB: 'Relationship Building', themesA: ['Activator'], themesB: ['Harmony'] },
  { id: '57', domainA: 'Influencing', domainB: 'Relationship Building', themesA: ['Command'], themesB: ['Empathy', 'Individualization'] },
  { id: '58', domainA: 'Influencing', domainB: 'Relationship Building', themesA: ['Communication'], themesB: ['Relator'] },
  { id: '59', domainA: 'Influencing', domainB: 'Relationship Building', themesA: ['Competition'], themesB: ['Includer'] },
  { id: '60', domainA: 'Influencing', domainB: 'Relationship Building', themesA: ['Maximizer'], themesB: ['Developer'] },
  { id: '61', domainA: 'Influencing', domainB: 'Relationship Building', themesA: ['Self-Assurance'], themesB: ['Adaptability'] },
  { id: '62', domainA: 'Influencing', domainB: 'Relationship Building', themesA: ['Significance'], themesB: ['Connectedness'] },
  { id: '63', domainA: 'Influencing', domainB: 'Relationship Building', themesA: ['Woo'], themesB: ['Individualization'] },
  { id: '64', domainA: 'Influencing', domainB: 'Relationship Building', themesA: ['Activator'], themesB: ['Positivity'] },
  { id: '65', domainA: 'Influencing', domainB: 'Relationship Building', themesA: ['Command'], themesB: ['Harmony'] },
  { id: '66', domainA: 'Influencing', domainB: 'Relationship Building', themesA: ['Communication'], themesB: ['Empathy'] },
  { id: '67', domainA: 'Influencing', domainB: 'Relationship Building', themesA: ['Maximizer'], themesB: ['Includer'] },
  { id: '68', domainA: 'Influencing', domainB: 'Relationship Building', themesA: ['Significance'], themesB: ['Relator'] },
  { id: '69', domainA: 'Influencing', domainB: 'Relationship Building', themesA: ['Woo'], themesB: ['Connectedness'] },
  { id: '70', domainA: 'Influencing', domainB: 'Relationship Building', themesA: ['Self-Assurance'], themesB: ['Developer', 'Individualization'] },

  // Influencing vs Strategic Thinking
  { id: '71', domainA: 'Influencing', domainB: 'Strategic Thinking', themesA: ['Activator'], themesB: ['Intellection'] },
  { id: '72', domainA: 'Influencing', domainB: 'Strategic Thinking', themesA: ['Command'], themesB: ['Strategic'] },
  { id: '73', domainA: 'Influencing', domainB: 'Strategic Thinking', themesA: ['Communication'], themesB: ['Input'] },
  { id: '74', domainA: 'Influencing', domainB: 'Strategic Thinking', themesA: ['Competition'], themesB: ['Analytical'] },
  { id: '75', domainA: 'Influencing', domainB: 'Strategic Thinking', themesA: ['Maximizer'], themesB: ['Learner'] },
  { id: '76', domainA: 'Influencing', domainB: 'Strategic Thinking', themesA: ['Self-Assurance'], themesB: ['Ideation'] },
  { id: '77', domainA: 'Influencing', domainB: 'Strategic Thinking', themesA: ['Significance'], themesB: ['Futuristic'] },
  { id: '78', domainA: 'Influencing', domainB: 'Strategic Thinking', themesA: ['Woo'], themesB: ['Context'] },
  { id: '79', domainA: 'Influencing', domainB: 'Strategic Thinking', themesA: ['Activator'], themesB: ['Strategic'] },
  { id: '80', domainA: 'Influencing', domainB: 'Strategic Thinking', themesA: ['Command'], themesB: ['Analytical'] },
  { id: '81', domainA: 'Influencing', domainB: 'Strategic Thinking', themesA: ['Communication'], themesB: ['Futuristic'] },
  { id: '82', domainA: 'Influencing', domainB: 'Strategic Thinking', themesA: ['Competition'], themesB: ['Ideation'] },
  { id: '83', domainA: 'Influencing', domainB: 'Strategic Thinking', themesA: ['Maximizer'], themesB: ['Intellection'] },
  { id: '84', domainA: 'Influencing', domainB: 'Strategic Thinking', themesA: ['Significance'], themesB: ['Input'] },
  { id: '85', domainA: 'Influencing', domainB: 'Strategic Thinking', themesA: ['Woo'], themesB: ['Learner'] },

  // Relationship Building vs Strategic Thinking
  { id: '86', domainA: 'Relationship Building', domainB: 'Strategic Thinking', themesA: ['Empathy'], themesB: ['Analytical'] },
  { id: '87', domainA: 'Relationship Building', domainB: 'Strategic Thinking', themesA: ['Harmony'], themesB: ['Strategic'] },
  { id: '88', domainA: 'Relationship Building', domainB: 'Strategic Thinking', themesA: ['Includer'], themesB: ['Ideation'] },
  { id: '89', domainA: 'Relationship Building', domainB: 'Strategic Thinking', themesA: ['Developer'], themesB: ['Learner'] },
  { id: '90', domainA: 'Relationship Building', domainB: 'Strategic Thinking', themesA: ['Adaptability'], themesB: ['Futuristic'] },
  { id: '91', domainA: 'Relationship Building', domainB: 'Strategic Thinking', themesA: ['Connectedness'], themesB: ['Context'] },
  { id: '92', domainA: 'Relationship Building', domainB: 'Strategic Thinking', themesA: ['Individualization'], themesB: ['Analytical'] },
  { id: '93', domainA: 'Relationship Building', domainB: 'Strategic Thinking', themesA: ['Positivity'], themesB: ['Intellection'] },
  { id: '94', domainA: 'Relationship Building', domainB: 'Strategic Thinking', themesA: ['Relator'], themesB: ['Input'] },
  { id: '95', domainA: 'Relationship Building', domainB: 'Strategic Thinking', themesA: ['Empathy'], themesB: ['Futuristic'] },
  { id: '96', domainA: 'Relationship Building', domainB: 'Strategic Thinking', themesA: ['Harmony'], themesB: ['Ideation'] },
  { id: '97', domainA: 'Relationship Building', domainB: 'Strategic Thinking', themesA: ['Includer'], themesB: ['Learner'] },
  { id: '98', domainA: 'Relationship Building', domainB: 'Strategic Thinking', themesA: ['Developer'], themesB: ['Strategic'] },
  { id: '99', domainA: 'Relationship Building', domainB: 'Strategic Thinking', themesA: ['Connectedness'], themesB: ['Intellection'] },
  { id: '100', domainA: 'Relationship Building', domainB: 'Strategic Thinking', themesA: ['Positivity'], themesB: ['Context'] },
];
